#!/usr/bin/env python3
"""Build the "Ideas we heard" word-cloud data for /ai-impact/report/.

Not part of the site build. Run it when the design team's whirl-data export
changes, then commit the JSON it writes.

Usage:
  python3 build_ideas_cloud.py [whirl-data.js] [whirl-finale-layout.js]

Defaults point at ../../../engaged_prototypes/ideas-cloud/ next to this repo.
The inputs are the design team's exports (generated by design/whirl_data.py
in their repo from the poll and discussion CSVs). They are NOT committed: the
poll set names ideas raised by a single respondent, some in that
respondent's own words, and the pipeline's privacy floor has not been
applied. Only the top KEEP poll ideas make it into the JSON.

Reads:
  whirl-data.js           window.WHIRL_DATA = { subthemes, phase1[{label,
                          subtheme, count}], phase2[{label, subtheme, votes}] }
  whirl-finale-layout.js  window.WHIRL_FINALE_LAYOUTS = { "1400x820": {...} }
                          the kept Phase 2 arrangement (positions per label)

Writes:
  ../../src/public/data/ai-report-ideas-cloud.json
  Shape (consumed by src/js/ai-impact-report/ideas-cloud.js):
    subthemes[{name, color}]
    poll[{label, subtheme, count}]        top KEEP ideas, sentence case
    pollTotal                             how many poll ideas there were
    discussion[{label, subtheme, votes}]  the 27 ideas
    keptLayouts{"WxH": {field, fontMultiplier, fontProbe, items[...]}}
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTOTYPES = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "engaged_prototypes", "ideas-cloud")
)
OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "src", "public", "data", "ai-report-ideas-cloud.json")
)

# 9/23: ship the top 55%; 9/29: 65% (229 of 352 with the 9/15 Phase 1 export)
# so compact scripts (Korean, Chinese) can draw more than English's 194. The
# cloud is laid out in a field larger than its frame so the faded outer ideas
# run past the edge; the JS decides how many to draw. The tail fade is a
# rendering choice and lives in the JS module.
KEEP_SHARE = 0.65

# Sentence case: lowercase everything except the first letter, tokens with two
# or more capitals (AI, UBI, LLMs, TK-12, TSMC's, US-Mexico, PhD ...) and these
# named things.
KEEP_PHRASES = [
    "California", "Californians", "CalCare", "Ponzi", "Taft Hartley Act", "MAD Act",
    "Delta Tunnels", "High Speed Rail", "Life-First Decision Invariant",
    "No Robo Bosses", "No Spying", "Citizen United", "Climate Corps",
    "State Library", "State Website", "China", "American", "Latino", "Microsoft",
    "Linux", "Apple", "Meta", "Google", "Amazon", "Gen X", "University of California",
    "Siskiyou County",
]

# 9/25: too many poll ideas started with "Regulate" (17 of 185, several of the
# biggest words in the cloud), so it read as "Regulate, Regulate, Regulate".
# Reworded with varied, neutral verbs while keeping the respondent's meaning.
# Keyed on the label after sentence_case(); "Regulate artificial intelligence"
# (the 9/15 export's successor to plain "Regulate AI") is left alone as the
# plain anchor. Re-keyed 9/29 for the 9/15 export's wording (23 of 194).
RELABEL = {
    "Regulate AI development and use": "Put guardrails on how AI is built and used",
    "Regulate AI in the workplace": "Set rules for AI in the workplace",
    "Regulate data centers": "Set standards for data centers",
    "Regulate and adopt AI": "Bring AI in with clear oversight",
    "Regulate AI companies": "Oversee AI companies",
    "Regulate AI to protect creators' rights": "Protect creators’ rights from AI",
    "Regulate AI data centers": "Limit AI data centers’ impact",
    "Regulate AI environmental impact": "Limit AI’s environmental impact",
    "Regulate AI data privacy": "Protect personal data from AI",
    "Regulate AI strictly": "Tighten the rules on AI",
    "Regulate AI-related layoffs": "Protect workers from AI-driven layoffs",
    "Regulate AI in education": "Set rules for AI in schools",
    "Regulate AI in healthcare": "Set rules for AI in healthcare",
    "Regulate private equity firms to prevent them from buying all available housing": "Stop private equity from buying up housing",
    "Regulate noise from data centers": "Limit data center noise",
    "Regulate AI adoption in corporations by requiring audits of user productivity vs AI productivity cost metrics": "Audit AI’s productivity impact in corporations",
    "Regulate AI image generation": "Set rules for AI image generation",
    "Regulate AI so that workers are trained to upskill in AI": "Require AI upskilling for workers",
    "Regulate AI if there is corruption or unfairness": "Address AI corruption or unfairness",
    "Regulate AI companies like a16z": "Oversee AI companies like a16z",
    "Regulate prediction markets": "Oversee prediction markets",
    "Regulate the venture capital industry": "Oversee the venture capital industry",
    "License High-Risk AI systems": "License high-risk AI systems",
    "Regulate AI systems that imitate voices to prevent financial theft": "Stop AI voice imitation used for financial theft",
    "Regulate the use of AI in drafting court documents": "Set rules for AI in court filings",
    "Change the structure of governance to AI-Assisted direct democracy": "Change the structure of governance to AI-assisted direct democracy",
    "Limit the powers of open AI and anthropic": "Limit the powers of OpenAI and Anthropic",
    "Regulate AI in social media": "Set rules for AI in social media",
    "Regulate data centers to have mandatory kill switches that shut off during peak power times": "Require data center kill switches for peak power times",
    "Regulate the use of venture capital in generative AI": "Oversee venture capital in generative AI",
    "Regulate AI like it regulates wall street": "Oversee AI like Wall Street",
    "Regulate AI to require human-created base for AI-generated content": "Require a human-created base for AI-generated content",
    "Regulate AI and corporations to facilitate public education and awareness": "Oversee AI and corporations to build public awareness",
    "Regulate the use of LLMs to ensure consumers receive compensation": "Ensure consumers are compensated for LLM use",
    "Define Human-Generated content": "Define human-generated content",
    "Regulate AI hyperscalers": "Oversee AI hyperscalers",
}

# 9/29: ideas raised by at least this many people are the cloud's big words
# and keep their place by count whatever their topic. Below it, AI-related
# ideas go first and NOT_AI ideas only fill whatever room is left, so the
# faded tail reads as being about AI. Size always stays the real count.
BIG_COUNT = 15

# 9/29: small ideas that are about work or the economy but not AI. Ideas
# about job loss, retraining and job transitions count as AI-related (the
# project is AI's impact on work), so they aren't listed. Keyed on the
# displayed label (after sentence_case() and RELABEL).
NOT_AI = {
    "Ban job offshoring", "Fund public transportation", "Promote employee ownership",
    "Prioritize transparency", "Promote renewable energy",
    "Build the Delta Tunnels and the High Speed Rail", "Implement energy utility gouging protections",
    "Raise taxes", "Not tax income under $60,000", "Provide affordable workspace",
    "Improve housing assistance programs for freelancers", "Cap CEO pay",
    "Improve math education to focus on implementing algorithms",
    "Stop private equity from buying up housing",
    "Implement all recommendations with 80% support from the assembly",
    "Repeal the Taft Hartley Act",
    "Close loopholes of abuse of worker visas in the tech industry",
    "Sponsor technology that helps Californians", "Implement student loan forgiveness",
    "Not issue work visas to individuals without a PhD in AI or fields with enough US citizens",
    "Stop taxing low earners",
    "Prohibit companies from using contract work through staff agencies to avoid paying benefits",
    "Tax loans against equity as income",
    "Tech companies should reinvest their profits in public goods and social needs",
    "Replace personal income tax with VAT",
    "Increase oversight of public universities' spending on new technologies",
    "Take action against price fixing", "Promote media literacy in schools",
    "Use revenue from taxing billionaires to fund single payer health care for Californians",
    "Stop companies from using shell companies to hide money",
    "Make consequences for violating worker protections personally accountable to responsible individuals",
    "Implement checks and balances on bias in workplace hiring, including boards",
    "Clarify the difference in water provision to industry versus households", "Fund manufacturing plants for electronics",
    "Assess industry input on regulation",
    "Criminalize wage theft", "Prevent leveraged buyouts",
    "Not shut down nuclear power facilities without modern replacements",
    "Oversee prediction markets", "Strengthen anti-discrimination enforcement", "Tax estates",
    "Oversee the venture capital industry", "Provide free childcare", "Implement a VAT tax",
    "Implement fire prevention measures in electrical infrastructure",
    "Prevent stock buybacks",
    "Increase employee net earnings",
    "California should investigate Meta, Google, and Amazon for artificially inflating their stock prices", "Implement a land value tax",
    "Make it easy for California students to attend University of California debt free",
    "California should raise the living wages for civil servants, nurses, doctors, and teachers",
    "Companies should keep their headquarters in California", "Regulate PG&E",
    "Regulate electrical power consumption",
    "Punish corporations for making people do multiple rounds of interviews for low-wage jobs and then decline them",
    "Require AI industry to provide free solar home power systems to California residents",
    "Create jobs that focus on restoring the planet", "Increase transparency in corporate ownership",
    "Ban dynamic pricing", "Not restrict services for the homeless", "Conserve energy and water",
    "Ensure elections are fair", "Establish laws to prevent wealthy people from hiding their incomes",
    "Ban third-party contractors and vendors in the job hiring process", "Build more housing",
    "Invest in infrastructure repair", "Allow tech companies to write off employee wages as capital expenses",
    "California should institute a semi-mandatory 2-year work rotation in agriculture or a trade after high school", "Implement a rent freeze",
    "Tax stock holdings",
    "Invest in educational programs for nuclear power plants, engineering, electrical, and robotics",
    "Require universities to consult faculty and students before entering contracts for new technologies",
    "Establish a commission to oversee the sovereign wealth fund and its redistribution",
}

# Ideas dropped outright: unclear, off-topic, or inflammatory as a policy
# idea even after sentence_case/RELABEL ("Acquire success", 9/25: unclear
# what "Success" means). The next idea in line takes the slot. Keyed on the
# displayed label (after sentence_case() and RELABEL).
EXCLUDE = {
    "Acquire success", "Restrict job eligibility",
    "Require proper grammar in all official documentation", "Ban AI in several spaces",
    "Imprison those who sell generative AI",
    "State of CA should consider moving from Microsoft products to Linux or Apple platforms",
    "Create jobs for AI ethical historians", "Stop forcing DEI biases onto AI",
    "Arrest AI company CEOs and shareholders",
    "Make generative AI systems inaccessible to capitalist companies",
    "Make suggestions based on monitoring AI models", "Move decision-makers close to the work itself",
    "Give the populace a relief check using money from bailing out tech companies",
    "Require language proficiency tests for government and certain other positions",
    "Oust the current federal administration",
    "Prohibit restricting websites that require data collection",
    "Back-fill the federal program to move food from farms to classrooms",
    "Increase unemployment rates for Gen X to make it livable while they search for jobs",
    "Allow funds and resources to be shifted fluidly",
    "Ban the president from using AI to push harmful propaganda", "Ensure work is done with ethics",
    "Reduce knowledge worker jobs", "Arrest individuals with over $100 million",
    "Restrict resource accumulation", "Disallow the branding of AI for language learning models",
    "Not pay or provide healthcare for robots",
    "Not intervene to prevent AI from negatively impacting the economy",
}

# whirl_data.py strips a leading "Government should"; the plural slips past it.
GOVERNMENTS_SHOULD = re.compile(r"^Governments should\s+", re.IGNORECASE)


def sentence_case(label):
    tokens = label.split(" ")
    out = " ".join(
        t if len(re.sub(r"[^A-Z]", "", t)) >= 2 else t.lower() for t in tokens
    )
    for phrase in KEEP_PHRASES:
        out = re.sub(rf"\b{re.escape(phrase)}\b", phrase, out, flags=re.IGNORECASE)
    return out[:1].upper() + out[1:]


def display_label(raw):
    s = sentence_case(GOVERNMENTS_SHOULD.sub("", raw))
    return RELABEL.get(s, s)


def read_js_object(path):
    """Pull the JSON object literal out of a `window.X = {...};` script."""
    text = open(path, encoding="utf-8").read()
    return json.loads(text[text.index("{") : text.rindex("}") + 1])


def main():
    data_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(PROTOTYPES, "whirl-data.js")
    layout_path = (
        sys.argv[2] if len(sys.argv) > 2 else os.path.join(PROTOTYPES, "whirl-finale-layout.js")
    )
    data = read_js_object(data_path)
    layouts = read_js_object(layout_path) if os.path.exists(layout_path) else {}

    phase1_all = sorted(data["phase1"], key=lambda c: -c["count"])  # stable: keeps file order among ties
    keep = max(1, round(len(phase1_all) * KEEP_SHARE))  # off the true total, so EXCLUDE doesn't shift the cutoff
    shown = [dict(c, label=display_label(c["label"])) for c in phase1_all]
    for name, labels in (("RELABEL", RELABEL.values()), ("NOT_AI", NOT_AI), ("EXCLUDE", EXCLUDE)):
        missing = set(labels) - {c["label"] for c in shown}
        if missing:
            sys.exit(f"{name} names labels not in the data: {sorted(missing)}")
    phase1 = [c for c in shown if c["label"] not in EXCLUDE]
    # Stable sort: big ideas by count, then AI-related small ideas, then the rest.
    phase1.sort(key=lambda c: 0 if c["count"] >= BIG_COUNT else 2 if c["label"] in NOT_AI else 1)
    poll = [
        {"label": c["label"], "subtheme": c["subtheme"], "count": c["count"]}
        for c in phase1[:keep]
    ]
    discussion = [
        {"label": c["label"], "subtheme": c["subtheme"], "votes": c["votes"]}
        for c in data["phase2"]
    ]
    kept = {}
    for key, lay in layouts.items():
        kept[key] = {
            "field": lay["field"],
            "fontMultiplier": lay["fontMultiplier"],
            "fontProbe": lay.get("fontProbe"),
            "pack": lay.get("pack"),
            "items": [
                {k: it[k] for k in ("label", "x", "y", "fontSize", "lines", "subtheme")}
                for it in lay["items"]
            ],
        }

    out = {
        "subthemes": [{"name": s["fullName"], "color": s["color"]} for s in data["subthemes"]],
        "pollTotal": len(phase1_all),
        "poll": poll,
        "discussion": discussion,
        "keptLayouts": kept,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print(f"wrote {OUT}: {len(poll)} of {len(phase1_all)} poll ideas ({len(phase1_all) - len(phase1)} excluded), {len(discussion)} discussion ideas, kept layouts {list(kept)}")


if __name__ == "__main__":
    main()
