#!/usr/bin/env python3
"""Build the "Ideas we heard" word-cloud data for /ai-impact/report/.

Not part of the site build. Run it when the design team's whirl-data export
changes, then commit the JSON it writes.

Usage:
  python3 build_ideas_cloud.py [whirl-data.js] [whirl-finale-layout.js]

Defaults point at ../../../engaged_prototypes/ideas-cloud/ next to this repo.
The inputs are the design team's exports (generated by design/whirl_data.py
in their repo from the poll and discussion CSVs). They are NOT committed: the
poll set names ideas raised by a single respondent, some in that
respondent's own words, and the pipeline's privacy floor has not been
applied. Only the top KEEP poll ideas make it into the JSON.

Reads:
  whirl-data.js           window.WHIRL_DATA = { subthemes, phase1[{label,
                          subtheme, count}], phase2[{label, subtheme, votes}] }
  whirl-finale-layout.js  window.WHIRL_FINALE_LAYOUTS = { "1400x820": {...} }
                          the kept Phase 2 arrangement (positions per label)

Writes:
  ../../src/public/data/ai-report-ideas-cloud.json
  Shape (consumed by src/js/ai-impact-report/ideas-cloud.js):
    subthemes[{name, color}]
    poll[{label, subtheme, count}]        top KEEP ideas, sentence case
    pollTotal                             how many poll ideas there were
    discussion[{label, subtheme, votes}]  the 27 ideas
    keptLayouts{"WxH": {field, fontMultiplier, fontProbe, items[...]}}
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTOTYPES = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "engaged_prototypes", "ideas-cloud")
)
OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "src", "public", "data", "ai-report-ideas-cloud.json")
)

# 9/23: ship the top 55% (185 of 337). The cloud is laid out in a field larger than
# its frame so the faded outer ideas run past the edge; the JS decides how many to draw. The tail fade is
# a rendering choice and lives in the JS module.
KEEP_SHARE = 0.55

# Sentence case: lowercase everything except the first letter, tokens with two
# or more capitals (AI, UBI, LLMs, TK-12, TSMC's, US-Mexico, PhD ...) and these
# named things.
KEEP_PHRASES = [
    "California", "Californians", "CalCare", "Ponzi", "Taft Hartley Act", "MAD Act",
    "Delta Tunnels", "High Speed Rail", "Life-First Decision Invariant",
    "No Robo Bosses", "No Spying", "Citizen United", "Climate Corps",
    "State Library", "State Website",
]

# 9/25: too many poll ideas started with "Regulate" (17 of 185, several of the
# biggest words in the cloud), so it read as "Regulate, Regulate, Regulate".
# Reworded with varied, neutral verbs while keeping the respondent's meaning.
# Keyed on the label after sentence_case(); "Regulate AI" itself is left alone
# as the plain anchor.
RELABEL = {
    "Regulate AI in employment": "Set rules for AI in the workplace",
    "Regulate AI development and use": "Put guardrails on how AI is built and used",
    "Regulate and utilize AI": "Use AI safely",
    "Regulate data centers": "Set standards for data centers",
    "Regulate AI companies": "Oversee AI companies",
    "Regulate AI data centers": "Oversee AI data centers",
    "Regulate AI copyright": "Enforce copyright rules for AI",
    "Regulate AI data privacy": "Protect personal data from AI",
    "Regulate AI labeling": "Require labels on AI content",
    "Regulate AI in court docs": "Set rules for AI in court filings",
    "Regulate AI to prevent intrusive emails and calls": "Stop intrusive AI calls and emails",
    "Regulate AI to prevent humanization": "Keep AI from passing as human",
    "Regulate electrical power consumption": "Manage electricity use",
    "Regulate the impact of AI on consumer electronics prices": "Keep AI from driving up electronics prices",
    "Regulate quality control of AI-generated software": "Set quality standards for AI-written software",
    "Regulate the venture capital industry": "Oversee the venture capital industry",
}


def sentence_case(label):
    tokens = label.split(" ")
    out = " ".join(
        t if len(re.sub(r"[^A-Z]", "", t)) >= 2 else t.lower() for t in tokens
    )
    for phrase in KEEP_PHRASES:
        out = re.sub(re.escape(phrase), phrase, out, flags=re.IGNORECASE)
    return out[:1].upper() + out[1:]


def read_js_object(path):
    """Pull the JSON object literal out of a `window.X = {...};` script."""
    text = open(path, encoding="utf-8").read()
    return json.loads(text[text.index("{") : text.rindex("}") + 1])


def main():
    data_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(PROTOTYPES, "whirl-data.js")
    layout_path = (
        sys.argv[2] if len(sys.argv) > 2 else os.path.join(PROTOTYPES, "whirl-finale-layout.js")
    )
    data = read_js_object(data_path)
    layouts = read_js_object(layout_path) if os.path.exists(layout_path) else {}

    phase1 = sorted(data["phase1"], key=lambda c: -c["count"])  # stable: keeps file order among ties
    keep = max(1, round(len(phase1) * KEEP_SHARE))
    poll = [
        {
            "label": RELABEL.get(sentence_case(c["label"]), sentence_case(c["label"])),
            "subtheme": c["subtheme"],
            "count": c["count"],
        }
        for c in phase1[:keep]
    ]
    discussion = [
        {"label": c["label"], "subtheme": c["subtheme"], "votes": c["votes"]}
        for c in data["phase2"]
    ]
    kept = {}
    for key, lay in layouts.items():
        kept[key] = {
            "field": lay["field"],
            "fontMultiplier": lay["fontMultiplier"],
            "fontProbe": lay.get("fontProbe"),
            "pack": lay.get("pack"),
            "items": [
                {k: it[k] for k in ("label", "x", "y", "fontSize", "lines", "subtheme")}
                for it in lay["items"]
            ],
        }

    out = {
        "subthemes": [{"name": s["fullName"], "color": s["color"]} for s in data["subthemes"]],
        "pollTotal": len(phase1),
        "poll": poll,
        "discussion": discussion,
        "keptLayouts": kept,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print(f"wrote {OUT}: {len(poll)} of {len(phase1)} poll ideas, {len(discussion)} discussion ideas, kept layouts {list(kept)}")


if __name__ == "__main__":
    main()
