#!/usr/bin/env python3
"""Build the "Ideas we heard" word-cloud data for /ai-impact/report/.

Not part of the site build. Run it when the design team's whirl-data export
changes, then commit the JSON it writes.

Usage:
  python3 build_ideas_cloud.py [whirl-data.js] [whirl-finale-layout.js]

Defaults point at ../../../engaged_prototypes/ideas-cloud/ next to this repo.
The inputs are the design team's exports (generated by design/whirl_data.py
in their repo from the poll and discussion CSVs). They are NOT committed: the
poll set names ideas raised by a single respondent, some in that
respondent's own words, and the pipeline's privacy floor has not been
applied. Only the top KEEP poll ideas make it into the JSON.

Reads:
  whirl-data.js           window.WHIRL_DATA = { subthemes, phase1[{label,
                          subtheme, count}], phase2[{label, subtheme, votes}] }
  whirl-finale-layout.js  window.WHIRL_FINALE_LAYOUTS = { "1400x820": {...} }
                          the kept Phase 2 arrangement (positions per label)

Writes:
  ../../src/public/data/ai-report-ideas-cloud.json
  Shape (consumed by src/js/ai-impact-report/ideas-cloud.js):
    subthemes[{name, color}]
    poll[{label, subtheme, count}]        top KEEP ideas, sentence case
    pollTotal                             how many poll ideas there were
    discussion[{label, subtheme, votes}]  the 27 ideas
    keptLayouts{"WxH": {field, fontMultiplier, fontProbe, items[...]}}
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROTOTYPES = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "engaged_prototypes", "ideas-cloud")
)
OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "src", "public", "data", "ai-report-ideas-cloud.json")
)

# 9/23: ship the top 55%; 9/29: 65% (229 of 352 with the 9/15 Phase 1 export)
# so compact scripts (Korean, Chinese) can draw more than English's 194. The
# cloud is laid out in a field larger than its frame so the faded outer ideas
# run past the edge; the JS decides how many to draw. The tail fade is a
# rendering choice and lives in the JS module.
KEEP_SHARE = 0.65

# Sentence case: lowercase everything except the first letter, tokens with two
# or more capitals (AI, UBI, LLMs, TK-12, TSMC's, US-Mexico, PhD ...) and these
# named things.
KEEP_PHRASES = [
    "California", "Californians", "CalCare", "Ponzi", "Taft Hartley Act", "MAD Act",
    "Delta Tunnels", "High Speed Rail", "Life-First Decision Invariant",
    "No Robo Bosses", "No Spying", "Citizen United", "Climate Corps",
    "State Library", "State Website", "China", "American", "Latino", "Microsoft",
    "Linux", "Apple", "Meta", "Google", "Amazon", "Gen X", "University of California",
]

# 9/25: too many poll ideas started with "Regulate" (17 of 185, several of the
# biggest words in the cloud), so it read as "Regulate, Regulate, Regulate".
# Reworded with varied, neutral verbs while keeping the respondent's meaning.
# Keyed on the label after sentence_case(); "Regulate artificial intelligence"
# (the 9/15 export's successor to plain "Regulate AI") is left alone as the
# plain anchor. Re-keyed 9/29 for the 9/15 export's wording (23 of 194).
RELABEL = {
    "Regulate AI development and use": "Put guardrails on how AI is built and used",
    "Regulate AI in the workplace": "Set rules for AI in the workplace",
    "Regulate data centers": "Set standards for data centers",
    "Regulate and adopt AI": "Bring AI in with clear oversight",
    "Regulate AI companies": "Oversee AI companies",
    "Regulate AI to protect creators' rights": "Protect creators’ rights from AI",
    "Regulate AI data centers": "Limit AI data centers’ impact",
    "Regulate AI environmental impact": "Limit AI’s environmental impact",
    "Regulate AI data privacy": "Protect personal data from AI",
    "Regulate AI strictly": "Tighten the rules on AI",
    "Regulate AI-related layoffs": "Protect workers from AI-driven layoffs",
    "Regulate AI in education": "Set rules for AI in schools",
    "Regulate AI in healthcare": "Set rules for AI in healthcare",
    "Regulate private equity firms to prevent them from buying all available housing": "Stop private equity from buying up housing",
    "Regulate noise from data centers": "Limit data center noise",
    "Regulate AI adoption in corporations by requiring audits of user productivity vs AI productivity cost metrics": "Audit AI’s productivity impact in corporations",
    "Regulate AI image generation": "Set rules for AI image generation",
    "Regulate AI so that workers are trained to upskill in AI": "Require AI upskilling for workers",
    "Regulate AI if there is corruption or unfairness": "Address AI corruption or unfairness",
    "Regulate AI companies like a16z": "Oversee AI companies like a16z",
    "Regulate prediction markets": "Oversee prediction markets",
    "Regulate the venture capital industry": "Oversee the venture capital industry",
    "License High-Risk AI systems": "License high-risk AI systems",
    "Regulate AI systems that imitate voices to prevent financial theft": "Stop AI voice imitation used for financial theft",
    "Regulate the use of AI in drafting court documents": "Set rules for AI in court filings",
    "Change the structure of governance to AI-Assisted direct democracy": "Change the structure of governance to AI-assisted direct democracy",
}

# 9/25: ambiguous, single-respondent ideas that made the KEEP_SHARE cutoff by
# count but don't read as a real policy idea even with sentence_case/RELABEL
# applied — drop them and let the next-ranked idea take the slot instead of
# just shipping it. ("Acquire Success", rawLabel "Government should acquire
# Success." — unclear what "Success" refers to.) Keyed on the label after
# sentence_case(), before RELABEL.
EXCLUDE = {
    "Acquire success",
}


def sentence_case(label):
    tokens = label.split(" ")
    out = " ".join(
        t if len(re.sub(r"[^A-Z]", "", t)) >= 2 else t.lower() for t in tokens
    )
    for phrase in KEEP_PHRASES:
        out = re.sub(rf"\b{re.escape(phrase)}\b", phrase, out, flags=re.IGNORECASE)
    return out[:1].upper() + out[1:]


def read_js_object(path):
    """Pull the JSON object literal out of a `window.X = {...};` script."""
    text = open(path, encoding="utf-8").read()
    return json.loads(text[text.index("{") : text.rindex("}") + 1])


def main():
    data_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(PROTOTYPES, "whirl-data.js")
    layout_path = (
        sys.argv[2] if len(sys.argv) > 2 else os.path.join(PROTOTYPES, "whirl-finale-layout.js")
    )
    data = read_js_object(data_path)
    layouts = read_js_object(layout_path) if os.path.exists(layout_path) else {}

    phase1_all = sorted(data["phase1"], key=lambda c: -c["count"])  # stable: keeps file order among ties
    keep = max(1, round(len(phase1_all) * KEEP_SHARE))  # off the true total, so EXCLUDE doesn't shift the cutoff
    phase1 = [c for c in phase1_all if sentence_case(c["label"]) not in EXCLUDE]
    poll = [
        {
            "label": RELABEL.get(sentence_case(c["label"]), sentence_case(c["label"])),
            "subtheme": c["subtheme"],
            "count": c["count"],
        }
        for c in phase1[:keep]
    ]
    discussion = [
        {"label": c["label"], "subtheme": c["subtheme"], "votes": c["votes"]}
        for c in data["phase2"]
    ]
    kept = {}
    for key, lay in layouts.items():
        kept[key] = {
            "field": lay["field"],
            "fontMultiplier": lay["fontMultiplier"],
            "fontProbe": lay.get("fontProbe"),
            "pack": lay.get("pack"),
            "items": [
                {k: it[k] for k in ("label", "x", "y", "fontSize", "lines", "subtheme")}
                for it in lay["items"]
            ],
        }

    out = {
        "subthemes": [{"name": s["fullName"], "color": s["color"]} for s in data["subthemes"]],
        "pollTotal": len(phase1_all),
        "poll": poll,
        "discussion": discussion,
        "keptLayouts": kept,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
        f.write("\n")
    print(f"wrote {OUT}: {len(poll)} of {len(phase1_all)} poll ideas ({len(phase1_all) - len(phase1)} excluded), {len(discussion)} discussion ideas, kept layouts {list(kept)}")


if __name__ == "__main__":
    main()
